# Generated by Django 4.2.7 on 2026-03-17 05:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_alter_property_id_alter_propertycategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.FileField(upload_to='view3d/scenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'obj'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='view3d/thumbnails/')),
                ('file_format', models.CharField(choices=[('glb', 'GLB'), ('gltf', 'glTF'), ('obj', 'OBJ')], default='glb', max_length=10)),
                ('status', models.CharField(choices=[('READY', 'Prete'), ('FAILED', 'Echec')], default='READY', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scenes_3d', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes_3d', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='view3d.scene3d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['scene', '-viewed_at'], name='view3d_scen_scene_i_5e8dcb_idx'), models.Index(fields=['user', '-viewed_at'], name='view3d_scen_user_id_2fd7e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scene3d',
            index=models.Index(fields=['property', '-created_at'], name='view3d_scen_propert_f2072e_idx'),
        ),
        migrations.AddIndex(
            model_name='scene3d',
            index=models.Index(fields=['property', 'is_published'], name='view3d_scen_propert_8ee6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='scene3d',
            index=models.Index(fields=['created_by', '-created_at'], name='view3d_scen_created_104dcd_idx'),
        ),
    ]
