# Generated by Django 6.0.2 on 2026-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence unique')),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('RENTED', 'Loué'), ('UNDER_WORK', 'En travaux')], default='VACANT', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surface (m²)')),
                ('rooms_count', models.PositiveIntegerField(verbose_name='Nombre de pièces')),
                ('description', models.TextField(blank=True)),
                ('base_rent_hc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loyer HC')),
                ('base_charges', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Charges')),
                ('guarantee_deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dépôt de garantie demandé')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/photos/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
