# Generated by Django 6.0.2 on 2026-03-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_deleted_at_property_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom du meuble/objet')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('condition', models.CharField(choices=[('NEUF', 'Neuf'), ('BON_ETAT', 'Bon état'), ('USE', 'Usagé'), ('MAUVAIS_ETAT', 'Mauvais état')], default='BON_ETAT', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
