# Generated by Django 6.0.2 on 2026-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyfurniture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertytype',
            unique_together={('category', 'name')},
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nom du meuble/objet'),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Nom du meuble/objet'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='propertytype',
            unique_together={('category', 'name'), ('category', 'name_en'), ('category', 'name_fr')},
        ),
    ]
