# Generated by Django 5.2.12 on 2026-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_id_alter_propertycategory_id_and_more'),
        ('properties', '0006_alter_propertytype_unique_together_and_more'),
    ]

    operations = [
    ]
