# Generated by Django 5.2.12 on 2026-03-19 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_merge_20260318_1933'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='propertycategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertycategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='propertyfurniture',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyfurniture',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Neuf'), ('GOOD', 'Bon état'), ('USED', 'Usagé'), ('BROKEN', 'Cassé/Abîmé')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyfurniture',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
