# Generated by Django 5.2.12 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tour_3d_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien 3D / Visite virtuelle'),
        ),
        migrations.AddField(
            model_name='propertyfurniture',
            name='tour_3d_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien 3D / Visite virtuelle'),
        ),
    ]
