# Generated by Django 6.0.2 on 2026-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('RENTED', 'Loué'), ('UNDER_WORK', 'En travaux'), ('RESERVED', 'Réservé')], default='VACANT', max_length=20),
        ),
    ]
