# Generated by Django 6.0.2 on 2026-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('UNPAID_RENT', 'Loyer impayé'), ('LEASE_END', 'Fin de bail proche'), ('RENT_REVISION', 'Révision de loyer possible'), ('LEASE_CREATED', 'Nouveau bail créé')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('related_entity_type', models.CharField(blank=True, max_length=100)),
                ('related_entity_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=20)),
                ('entity_name', models.CharField(max_length=100, verbose_name="Nom de l'entité (ex: Bien, Bail)")),
                ('entity_id', models.CharField(max_length=100, verbose_name="ID de l'entité")),
                ('details', models.JSONField(verbose_name='Détails (Anciennes/Nouvelles valeurs)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
