# Generated by Django 4.2.7 on 2026-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alert_id_alter_auditlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_actionable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Alerte système', max_length=180),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_app',
            field=models.CharField(blank=True, default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('UNPAID_RENT', 'Loyer impayé'), ('LEASE_END', 'Fin de bail proche'), ('RENT_REVISION', 'Révision de loyer possible'), ('LEASE_CREATED', 'Nouveau bail créé'), ('PAYMENT_DUE_SOON', 'Paiement bientôt dû'), ('PROPERTY_VACANT', 'Bien vacant')], max_length=40),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PAYMENT', 'Paiement'), ('ALERT', 'Alerte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Détails (Anciennes/Nouvelles valeurs)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_alert_recipie_f69fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-created_at'], name='core_alert_alert_t_aa335f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', '-created_at'], name='core_alert_priorit_2106c2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_name', 'entity_id'], name='core_auditl_entity__b13b97_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
    ]
