# Generated by Django 5.2.12 on 2026-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert_action_url_alert_due_at_alert_expires_at_and_more'),
        ('core', '0004_alter_alert_id_alter_auditlog_id'),
    ]

    operations = [
    ]
