# Generated by Django 6.0.2 on 2026-03-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_property_deleted_at_property_is_deleted_and_more'),
        ('users', '0003_guarantor_deleted_at_guarantor_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('loyer_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loyer_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depot_garantie_verse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depot_restitue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depot_retenue_motif', models.TextField(blank=True, null=True)),
                ('motif_fin', models.TextField(blank=True, null=True)),
                ('date_sortie_effective', models.DateField(blank=True, null=True)),
                ('etat_lieux_entree_url', models.URLField(blank=True, null=True)),
                ('etat_lieux_sortie_url', models.URLField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('jour_paiement', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('resilie', 'Résilié')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='users.tenantprofile')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
            },
        ),
        migrations.CreateModel(
            name='RentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_revision', models.DateField()),
                ('ancien_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField()),
                ('appliquee', models.BooleanField(default=False)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_revisions', to='leases.lease')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Révision de loyer',
                'verbose_name_plural': 'Révisions de loyer',
            },
        ),
    ]
