# Generated by Django 5.2.12 on 2026-03-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rentrevision',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rentrevision',
            name='is_deleted',
        ),
    ]
