# Generated by Django 6.0.2 on 2026-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
