# Generated by Django 5.2.12 on 2026-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_guarantor_id_alter_tenantprofile_id_and_more'),
        ('users', '0004_user_is_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
    ]
