# Generated by Django 5.2.12 on 2026-03-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260318_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='is_deleted',
        ),
    ]
