# Generated by Django 6.0.2 on 2026-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('justificatif_url', models.URLField(blank=True, null=True)),
                ('deductible', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépense',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('date_envoi', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('periode_mois', models.PositiveIntegerField()),
                ('periode_annee', models.PositiveIntegerField()),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('moyen', models.CharField(choices=[('virement', 'Virement'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paiement de loyer',
                'verbose_name_plural': 'Paiements de loyer',
            },
        ),
    ]
