# Generated by Django 6.0.2 on 2026-03-16 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('leases', '0001_initial'),
        ('properties', '0004_property_deleted_at_property_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property'),
        ),
        migrations.AddField(
            model_name='expense',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.expensecategory'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='bail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='paiement_loyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finances.rentpayment'),
        ),
        migrations.AlterUniqueTogether(
            name='rentpayment',
            unique_together={('bail', 'periode_mois', 'periode_annee')},
        ),
    ]
