# Generated by Django 5.2.12 on 2026-03-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='is_deleted',
        ),
    ]
